#property strict
#property version "1.00"
extern string ApiBaseUrl="https://forex.bridgesparkinnovation.com/api/v1/terminal";
extern string NodeCredential="";
extern int MagicNumber=26090601,PollSeconds=1,HttpTimeoutMs=8000,SlippagePoints=30;
long last_sequence=0;datetime last_heartbeat=0,last_snapshot=0;
string Esc(string v){StringReplace(v,"\\","\\\\");StringReplace(v,"\"","\\\"");return v;}string Iso(){MqlDateTime d;TimeToStruct(TimeGMT(),d);return StringFormat("%04d-%02d-%02dT%02d:%02d:%02dZ",d.year,d.mon,d.day,d.hour,d.min,d.sec);}string Uuid(){uint a=GetTickCount(),b=MathRand();return StringFormat("%08x-%04x-4%03x-8%03x-%08x%04x",a,b&0xffff,(a>>4)&0xfff,(b>>4)&0xfff,(uint)TimeLocal(),(a^b)&0xffff);}
string JS(string j,string k){string n="\""+k+"\"";int p=StringFind(j,n);if(p<0)return "";p=StringFind(j,":",p)+1;while(p<StringLen(j)&&StringGetChar(j,p)<=32)p++;if(StringGetChar(j,p)!=34)return "";p++;string o="";bool e=false;for(int i=p;i<StringLen(j);i++){int c=StringGetChar(j,i);if(e){o+=CharToString((uchar)c);e=false;}else if(c==92)e=true;else if(c==34)break;else o+=CharToString((uchar)c);}return o;}double JN(string j,string k){string s=JS(j,k);if(s!="")return StrToDouble(s);int p=StringFind(j,"\""+k+"\"");if(p<0)return 0;p=StringFind(j,":",p)+1;string n="";for(int i=p;i<StringLen(j);i++){int c=StringGetChar(j,i);if((c>=48&&c<=57)||c==45||c==46)n+=CharToString((uchar)c);else if(StringLen(n)>0)break;}return StrToDouble(n);}
int Req(string method,string path,string body,string &response){char data[],result[];string out_headers,headers="Authorization: Node "+NodeCredential+"\r\nContent-Type: application/json\r\n";StringToCharArray(body,data,0,WHOLE_ARRAY,CP_UTF8);ResetLastError();int code=WebRequest(method,ApiBaseUrl+path,headers,HttpTimeoutMs,data,result,out_headers);response=CharArrayToString(result,0,-1,CP_UTF8);if(code<0)Print("FX WebRequest failed: ",GetLastError());return code;}void Event(string cmd,string type,string payload){string r;Req("POST","/events","{\"event_id\":\""+Uuid()+"\",\"command_id\":\""+cmd+"\",\"event_type\":\""+type+"\",\"terminal_time\":\""+Iso()+"\",\"payload\":"+payload+"}",r);}
void Heartbeat(){string r;Req("POST","/heartbeat",StringFormat("{\"agent_version\":\"1.00\",\"terminal_build\":\"%d\",\"capabilities\":{\"platform\":\"MT4\",\"trade_allowed\":%s,\"connected\":%s}}",TerminalInfoInteger(TERMINAL_BUILD),IsTradeAllowed()?"true":"false",IsConnected()?"true":"false"),r);}void Snapshot(){string ps="[";bool first=true;for(int i=0;i<OrdersTotal();i++){if(!OrderSelect(i,SELECT_BY_POS,MODE_TRADES)||OrderType()>OP_SELL)continue;if(!first)ps+=",";first=false;double current=OrderType()==OP_BUY?MarketInfo(OrderSymbol(),MODE_BID):MarketInfo(OrderSymbol(),MODE_ASK);ps+=StringFormat("{\"position_ticket\":\"%d\",\"broker_symbol\":\"%s\",\"side\":\"%s\",\"volume\":\"%.2f\",\"current_price\":\"%s\",\"profit\":\"%.2f\"}",OrderTicket(),Esc(OrderSymbol()),OrderType()==OP_BUY?"BUY":"SELL",OrderLots(),DoubleToString(current,(int)MarketInfo(OrderSymbol(),MODE_DIGITS)),OrderProfit()+OrderSwap()+OrderCommission());}ps+="]";string r;Req("POST","/snapshots",StringFormat("{\"sequence\":%d,\"captured_at\":\"%s\",\"account\":{\"balance\":\"%.2f\",\"equity\":\"%.2f\"},\"orders\":[],\"positions\":%s}",last_sequence,Iso(),AccountBalance(),AccountEquity(),ps),r);}
void Execute(string j){string cmd=JS(j,"command_id"),kind=JS(j,"kind"),symbol=JS(j,"canonical_symbol"),side=JS(j,"side"),type=JS(j,"type");long seq=(long)JN(j,"sequence");double lots=JN(j,"volume"),price=JN(j,"price"),sl=JN(j,"stop_loss"),tp=JN(j,"take_profit");int pos=(int)JN(j,"position_ticket");if(seq<=last_sequence){Event(cmd,"UNKNOWN","{\"code\":\"STALE_SEQUENCE\",\"message\":\"Already processed\"}");return;}Event(cmd,"SUBMITTED","{\"message\":\"Submitted to MT4\"}");int ticket=-1,error=0;double fill=0;if(kind=="CLOSE"&&pos>0&&OrderSelect(pos,SELECT_BY_TICKET)){fill=OrderType()==OP_BUY?MarketInfo(OrderSymbol(),MODE_BID):MarketInfo(OrderSymbol(),MODE_ASK);if(OrderClose(pos,OrderLots(),fill,SlippagePoints,clrNONE))ticket=pos;else error=GetLastError();}else if(kind=="PLACE"){int op=side=="BUY"?OP_BUY:OP_SELL;if(type=="LIMIT")op=side=="BUY"?OP_BUYLIMIT:OP_SELLLIMIT;else if(type=="STOP")op=side=="BUY"?OP_BUYSTOP:OP_SELLSTOP;if(type=="MARKET")price=side=="BUY"?MarketInfo(symbol,MODE_ASK):MarketInfo(symbol,MODE_BID);ticket=OrderSend(symbol,op,lots,price,SlippagePoints,sl,tp,"BridgeSpark FX",MagicNumber,0,clrNONE);if(ticket<0)error=GetLastError();else if(OrderSelect(ticket,SELECT_BY_TICKET))fill=OrderOpenPrice();}string payload=StringFormat("{\"code\":\"%d\",\"message\":\"terminal result\",\"filled_volume\":\"%.2f\",\"average_price\":\"%s\",\"execution_snapshot\":{\"broker_symbol\":\"%s\",\"position_ticket\":\"%d\",\"order_ticket\":\"%d\"}}",error,lots,DoubleToString(fill,(int)MarketInfo(symbol,MODE_DIGITS)),Esc(symbol),ticket,ticket);Event(cmd,ticket>=0?"FILLED":"REJECTED",payload);last_sequence=seq;}void Poll(){string r;if(Req("POST","/commands/claim",StringFormat("{\"platform\":\"MT4\",\"last_sequence\":%d}",last_sequence),r)==200)Execute(r);}
int OnInit(){if(NodeCredential=="")return INIT_PARAMETERS_INCORRECT;MathSrand(GetTickCount());EventSetTimer(MathMax(1,PollSeconds));return INIT_SUCCEEDED;}void OnDeinit(const int reason){EventKillTimer();}void OnTimer(){Poll();datetime n=TimeLocal();if(n-last_snapshot>=2){Snapshot();last_snapshot=n;}if(n-last_heartbeat>=30){Heartbeat();last_heartbeat=n;}}
