#property strict
#property version "1.00"
#include <Trade/Trade.mqh>
input string ApiBaseUrl="https://forex.bridgesparkinnovation.com/api/v1/terminal";
input string NodeCredential="";
input ulong MagicNumber=26090601;
input int PollSeconds=1, HttpTimeoutMs=8000, SlippagePoints=30;
CTrade trade; long last_sequence=0; datetime last_heartbeat=0,last_snapshot=0;
string Esc(string v){StringReplace(v,"\\","\\\\");StringReplace(v,"\"","\\\"");return v;}
string Iso(){MqlDateTime d;TimeToStruct(TimeGMT(),d);return StringFormat("%04d-%02d-%02dT%02d:%02d:%02dZ",d.year,d.mon,d.day,d.hour,d.min,d.sec);}
string Uuid(){uint a=(uint)GetTickCount(),b=(uint)MathRand();return StringFormat("%08x-%04x-4%03x-8%03x-%08x%04x",a,b&0xffff,(a>>4)&0xfff,(b>>4)&0xfff,(uint)TimeLocal(),(a^b)&0xffff);}
string JS(string j,string k){string n="\""+k+"\"";int p=StringFind(j,n);if(p<0)return "";p=StringFind(j,":",p)+1;while(p<StringLen(j)&&StringGetCharacter(j,p)<=32)p++;if(StringGetCharacter(j,p)!=34)return "";p++;string o="";bool e=false;for(int i=p;i<StringLen(j);i++){ushort c=StringGetCharacter(j,i);if(e){o+=ShortToString(c);e=false;}else if(c==92)e=true;else if(c==34)break;else o+=ShortToString(c);}return o;}
double JN(string j,string k){string s=JS(j,k);if(s!="")return StringToDouble(s);int p=StringFind(j,"\""+k+"\"");if(p<0)return 0;p=StringFind(j,":",p)+1;string n="";for(int i=p;i<StringLen(j);i++){ushort c=StringGetCharacter(j,i);if((c>=48&&c<=57)||c==45||c==46)n+=ShortToString(c);else if(StringLen(n)>0)break;}return StringToDouble(n);}
int Req(string method,string path,string body,string &response){char data[],result[];string out_headers,headers="Authorization: Node "+NodeCredential+"\r\nContent-Type: application/json\r\n";StringToCharArray(body,data,0,WHOLE_ARRAY,CP_UTF8);ResetLastError();int code=WebRequest(method,ApiBaseUrl+path,headers,HttpTimeoutMs,data,result,out_headers);response=CharArrayToString(result,0,-1,CP_UTF8);if(code<0)Print("FX WebRequest failed: ",GetLastError());return code;}
void Event(string cmd,string type,string payload){string r;Req("POST","/events","{\"event_id\":\""+Uuid()+"\",\"command_id\":\""+cmd+"\",\"event_type\":\""+type+"\",\"terminal_time\":\""+Iso()+"\",\"payload\":"+payload+"}",r);}
void Heartbeat(){string r;Req("POST","/heartbeat",StringFormat("{\"agent_version\":\"1.00\",\"terminal_build\":\"%d\",\"capabilities\":{\"platform\":\"MT5\",\"trade_allowed\":%s,\"connected\":%s}}",(int)TerminalInfoInteger(TERMINAL_BUILD),TerminalInfoInteger(TERMINAL_TRADE_ALLOWED)?"true":"false",TerminalInfoInteger(TERMINAL_CONNECTED)?"true":"false"),r);}
void Snapshot(){string ps="[";bool first=true;for(int i=0;i<PositionsTotal();i++){ulong t=PositionGetTicket(i);if(!t||!PositionSelectByTicket(t))continue;if(!first)ps+=",";first=false;string s=PositionGetString(POSITION_SYMBOL);ps+=StringFormat("{\"position_ticket\":\"%I64u\",\"broker_symbol\":\"%s\",\"side\":\"%s\",\"volume\":\"%.4f\",\"current_price\":\"%.*f\",\"profit\":\"%.2f\"}",t,Esc(s),PositionGetInteger(POSITION_TYPE)==POSITION_TYPE_BUY?"BUY":"SELL",PositionGetDouble(POSITION_VOLUME),(int)SymbolInfoInteger(s,SYMBOL_DIGITS),PositionGetDouble(POSITION_PRICE_CURRENT),PositionGetDouble(POSITION_PROFIT));}ps+="]";string r;Req("POST","/snapshots",StringFormat("{\"sequence\":%I64d,\"captured_at\":\"%s\",\"account\":{\"balance\":\"%.2f\",\"equity\":\"%.2f\"},\"orders\":[],\"positions\":%s}",last_sequence,Iso(),AccountInfoDouble(ACCOUNT_BALANCE),AccountInfoDouble(ACCOUNT_EQUITY),ps),r);}
void Execute(string j){string cmd=JS(j,"command_id"),kind=JS(j,"kind"),symbol=JS(j,"canonical_symbol"),side=JS(j,"side"),type=JS(j,"type");long seq=(long)JN(j,"sequence");double vol=JN(j,"volume"),price=JN(j,"price"),sl=JN(j,"stop_loss"),tp=JN(j,"take_profit");ulong ticket=(ulong)JN(j,"position_ticket");if(seq<=last_sequence){Event(cmd,"UNKNOWN","{\"code\":\"STALE_SEQUENCE\",\"message\":\"Already processed\"}");return;}SymbolSelect(symbol,true);trade.SetExpertMagicNumber(MagicNumber);trade.SetDeviationInPoints(SlippagePoints);trade.SetAsyncMode(false);Event(cmd,"SUBMITTED","{\"message\":\"Submitted to MT5\"}");bool ok=false;if(kind=="CLOSE")ok=ticket>0&&trade.PositionClose(ticket);else if(kind=="PLACE"&&type=="MARKET")ok=side=="BUY"?trade.Buy(vol,symbol,0,sl,tp):trade.Sell(vol,symbol,0,sl,tp);else if(kind=="PLACE"&&type=="LIMIT")ok=side=="BUY"?trade.BuyLimit(vol,price,symbol,sl,tp):trade.SellLimit(vol,price,symbol,sl,tp);else if(kind=="PLACE"&&type=="STOP")ok=side=="BUY"?trade.BuyStop(vol,price,symbol,sl,tp):trade.SellStop(vol,price,symbol,sl,tp);ulong deal=trade.ResultDeal();double fill=0;if(deal&&HistoryDealSelect(deal))fill=HistoryDealGetDouble(deal,DEAL_PRICE);string payload=StringFormat("{\"code\":\"%u\",\"message\":\"%s\",\"filled_volume\":\"%.4f\",\"average_price\":\"%.*f\",\"execution_snapshot\":{\"broker_symbol\":\"%s\",\"position_ticket\":\"%I64u\",\"order_ticket\":\"%I64u\",\"deal_ticket\":\"%I64u\"}}",trade.ResultRetcode(),Esc(trade.ResultRetcodeDescription()),vol,(int)SymbolInfoInteger(symbol,SYMBOL_DIGITS),fill,Esc(symbol),trade.ResultOrder(),trade.ResultOrder(),deal);string state="REJECTED";uint ret=trade.ResultRetcode();if(ok){if(ret==TRADE_RETCODE_DONE_PARTIAL)state="PARTIAL";else if(ret==TRADE_RETCODE_PLACED||deal==0)state="ACCEPTED";else state="FILLED";}Event(cmd,state,payload);last_sequence=seq;}
void Poll(){string r;if(Req("POST","/commands/claim",StringFormat("{\"platform\":\"MT5\",\"last_sequence\":%I64d}",last_sequence),r)==200)Execute(r);}
int OnInit(){if(NodeCredential=="")return INIT_PARAMETERS_INCORRECT;MathSrand((int)GetTickCount());EventSetTimer(MathMax(1,PollSeconds));return INIT_SUCCEEDED;}void OnDeinit(const int reason){EventKillTimer();}void OnTimer(){Poll();datetime n=TimeLocal();if(n-last_snapshot>=2){Snapshot();last_snapshot=n;}if(n-last_heartbeat>=30){Heartbeat();last_heartbeat=n;}}
