# Generated by Django 5.2.17 on 2026-09-06 10:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField()),
                ('is_active', models.BooleanField(default=True)),
                ('webhook_secret_ciphertext', models.TextField(blank=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='strategies', to='tenancy.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='TradingAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('MT4', 'Mt4'), ('MT5', 'Mt5')], max_length=3)),
                ('account_mode', models.CharField(choices=[('MT4_TICKETS', 'Mt4 Tickets'), ('MT5_HEDGING', 'Mt5 Hedging'), ('MT5_NETTING', 'Mt5 Netting')], max_length=16)),
                ('broker_name', models.CharField(max_length=160)),
                ('broker_server', models.CharField(max_length=160)),
                ('login', models.CharField(max_length=64)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('leverage', models.PositiveIntegerField(blank=True, null=True)),
                ('is_demo', models.BooleanField(default=False)),
                ('is_enabled', models.BooleanField(default=True)),
                ('last_equity', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('last_balance', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trading_accounts', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trading_accounts', to='tenancy.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='TradeIntent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('MANUAL', 'Manual'), ('WEBHOOK', 'Webhook'), ('STRATEGY', 'Strategy'), ('COPY', 'Copy'), ('STOP_LOSS', 'Stop Loss'), ('TAKE_PROFIT', 'Take Profit'), ('KILL_SWITCH', 'Kill Switch'), ('RECONCILIATION', 'Reconciliation')], max_length=24)),
                ('action', models.CharField(choices=[('OPEN', 'Open'), ('CLOSE', 'Close'), ('MODIFY', 'Modify'), ('CANCEL', 'Cancel')], max_length=12)),
                ('state', models.CharField(choices=[('RECEIVED', 'Received'), ('VALIDATED', 'Validated'), ('QUEUED', 'Queued'), ('CLAIMED', 'Claimed'), ('SUBMITTED', 'Submitted'), ('ACCEPTED', 'Accepted'), ('PARTIAL', 'Partial'), ('FILLED', 'Filled'), ('RECONCILED', 'Reconciled'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('UNKNOWN', 'Unknown')], default='RECEIVED', max_length=16)),
                ('idempotency_key', models.CharField(max_length=160)),
                ('canonical_symbol', models.CharField(max_length=64)),
                ('side', models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], max_length=4)),
                ('order_type', models.CharField(max_length=16)),
                ('requested_volume', models.DecimalField(decimal_places=4, max_digits=12)),
                ('filled_volume', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('requested_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('take_profit', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('request_snapshot', models.JSONField(default=dict)),
                ('execution_snapshot', models.JSONField(blank=True, default=dict)),
                ('failure_code', models.CharField(blank=True, max_length=64)),
                ('failure_message', models.TextField(blank=True)),
                ('parent_intent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_intents', to='trading.tradeintent')),
                ('strategy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trading.strategy')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trade_intents', to='tenancy.tenant')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trade_intents', to='trading.tradingaccount')),
            ],
        ),
        migrations.CreateModel(
            name='RiskProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('max_lot_per_order', models.DecimalField(decimal_places=4, max_digits=12)),
                ('max_open_lots', models.DecimalField(decimal_places=4, max_digits=12)),
                ('max_daily_loss', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('max_daily_profit', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('max_spread_points', models.PositiveIntegerField(blank=True, null=True)),
                ('max_slippage_points', models.PositiveIntegerField(blank=True, null=True)),
                ('trading_enabled', models.BooleanField(default=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_profile', to='trading.tradingaccount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canonical_symbol', models.CharField(max_length=64)),
                ('broker_symbol', models.CharField(max_length=64)),
                ('side', models.CharField(max_length=4)),
                ('broker_position_ticket', models.CharField(blank=True, max_length=64)),
                ('broker_order_ticket', models.CharField(blank=True, max_length=64)),
                ('volume', models.DecimalField(decimal_places=4, max_digits=12)),
                ('open_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('take_profit', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('is_open', models.BooleanField(default=True)),
                ('broker_snapshot', models.JSONField(default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='tenancy.tenant')),
                ('opening_intent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_positions', to='trading.tradeintent')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='trading.tradingaccount')),
            ],
        ),
        migrations.CreateModel(
            name='CopyRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocation', models.CharField(choices=[('FIXED_LOT', 'Fixed Lot'), ('EQUITY_RATIO', 'Equity Ratio'), ('BALANCE_RATIO', 'Balance Ratio'), ('RISK_PERCENT', 'Risk Percent')], max_length=20)),
                ('allocation_value', models.DecimalField(decimal_places=4, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('symbol_map', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='copy_relationships', to='tenancy.tenant')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='copy_leaders', to='trading.tradingaccount')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='copy_followers', to='trading.tradingaccount')),
            ],
        ),
        migrations.AddConstraint(
            model_name='strategy',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='unique_tenant_strategy'),
        ),
        migrations.AddConstraint(
            model_name='tradingaccount',
            constraint=models.UniqueConstraint(fields=('tenant', 'platform', 'broker_server', 'login'), name='unique_terminal_account'),
        ),
        migrations.AddIndex(
            model_name='tradeintent',
            index=models.Index(fields=['tenant', 'state', 'created_at'], name='trading_tra_tenant__78922b_idx'),
        ),
        migrations.AddIndex(
            model_name='tradeintent',
            index=models.Index(fields=['account', 'state', 'created_at'], name='trading_tra_account_281208_idx'),
        ),
        migrations.AddConstraint(
            model_name='tradeintent',
            constraint=models.UniqueConstraint(fields=('account', 'idempotency_key'), name='unique_account_intent'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['account', 'is_open', 'canonical_symbol'], name='trading_pos_account_9da6bf_idx'),
        ),
        migrations.AddConstraint(
            model_name='copyrelationship',
            constraint=models.UniqueConstraint(fields=('leader', 'follower'), name='unique_copy_relationship'),
        ),
        migrations.AddConstraint(
            model_name='copyrelationship',
            constraint=models.CheckConstraint(condition=models.Q(('leader', models.F('follower')), _negated=True), name='copy_accounts_differ'),
        ),
    ]
