import { useCallback, useEffect, useState } from "react";
import { Activity, Copy, LayoutDashboard, Radio, Settings, ShieldCheck, WalletCards } from "lucide-react";
import { api, login } from "./api";

type Branding={name:string;branding:{primary_color?:string}};
type Account={id:string;platform:string;broker_name:string;broker_server:string;login:string;connection_status:string};
type Intent={id:string;source:string;action:string;canonical_symbol:string;side:string;state:string;requested_volume:string;failure_message?:string};
type Position={id:string;account:string;broker_symbol:string;side:string;volume:string;open_price:string;current_price?:string;stop_loss?:string;take_profit?:string;is_open:boolean};
type Strategy={id:string;name:string;slug:string;is_active:boolean};
const nav=[[LayoutDashboard,"Overview"],[WalletCards,"Accounts"],[Activity,"Orders & Positions"],[Radio,"Strategies"],[Copy,"Copy Trading"],[ShieldCheck,"Risk Controls"],[Settings,"Settings"]] as const;

export default function Console(){
 const[auth,setAuth]=useState(!!localStorage.getItem("access_token"));const[branding,setBranding]=useState<Branding>({name:"FX",branding:{}});const[section,setSection]=useState("Overview");const[accounts,setAccounts]=useState<Account[]>([]);const[intents,setIntents]=useState<Intent[]>([]);const[positions,setPositions]=useState<Position[]>([]);const[strategies,setStrategies]=useState<Strategy[]>([]);const[message,setMessage]=useState("");
 const refresh=useCallback(async()=>{if(!localStorage.getItem("access_token"))return;try{const[a,i,p,s]=await Promise.all([api<Account[]>("/accounts"),api<Intent[]>("/intents"),api<Position[]>("/positions"),api<Strategy[]>("/strategies")]);setAccounts(a);setIntents(i);setPositions(p);setStrategies(s)}catch(e){setMessage(e instanceof Error?e.message:"Unable to load")}},[]);
 useEffect(()=>{api<Branding>("/branding").then(setBranding).catch(()=>{});refresh()},[auth,refresh]);
 const done=(s:string)=>{setMessage(s);refresh()};if(!auth)return <Login name={branding.name} done={()=>setAuth(true)}/>;
 return <div className="shell" style={{"--brand":branding.branding.primary_color||"#57e0a1"} as React.CSSProperties}><aside><div className="brand"><span>FX</span><div><strong>{branding.name}</strong><small>Trading command centre</small></div></div><nav>{nav.map(([I,n])=><button key={n} className={section===n?"active":""} onClick={()=>setSection(n)}><I size={18}/><span>{n}</span></button>)}</nav><div className="node-health"><span className="pulse"/>Execution network operational</div></aside><main><header><div><p>COMMAND CENTRE</p><h1>{section}</h1></div><div className="header-actions"><button className="secondary" onClick={refresh}>Refresh</button><button className="secondary" onClick={()=>{localStorage.clear();setAuth(false)}}>Sign out</button><button className="trade" onClick={()=>setSection("Orders & Positions")}>New manual trade</button></div></header>{message&&<div className="notice">{message}</div>}{section==="Overview"&&<Overview accounts={accounts} intents={intents}/>} {section==="Accounts"&&<Accounts items={accounts} done={done}/>} {section==="Orders & Positions"&&<Orders accounts={accounts} intents={intents} positions={positions} done={done}/>} {section==="Strategies"&&<Strategies items={strategies} done={done}/>} {section==="Copy Trading"&&<Panel title="Copy Trading"><p>Create leader-to-follower allocation relationships through the tenant API. The terminal execution engine preserves each follower account lock and idempotency key.</p></Panel>} {section==="Risk Controls"&&<Risk accounts={accounts} positions={positions} done={done}/>} {section==="Settings"&&<Panel title="MT4 / MT5 installation"><p>Provision a terminal credential under Accounts, install the matching Expert Advisor, allow this HTTPS domain in WebRequest, and attach the EA to one chart. Broker passwords stay inside MetaTrader.</p></Panel>}</main></div>
}
function Login({name,done}:{name:string;done:()=>void}){const[e,setE]=useState("");const[p,setP]=useState("");const[m,setM]=useState("");return <div className="login-page"><form className="login-card" onSubmit={async x=>{x.preventDefault();try{await login(e,p);done()}catch(q){setM(q instanceof Error?q.message:"Login failed")}}}><div className="login-mark">FX</div><p>SECURE TRADING CLOUD</p><h1>{name}</h1>{m&&<div className="error">{m}</div>}<label>Email<input type="email" value={e} onChange={x=>setE(x.target.value)} required/></label><label>Password<input type="password" value={p} onChange={x=>setP(x.target.value)} required/></label><button className="trade">Sign in</button></form></div>}
function Overview({accounts,intents}:{accounts:Account[];intents:Intent[]}){return <><section className="metrics"><Metric l="Connected accounts" v={`${accounts.filter(a=>a.connection_status==="CONNECTED").length}/${accounts.length}`}/><Metric l="Active instructions" v={String(intents.filter(i=>["QUEUED","CLAIMED","SUBMITTED","ACCEPTED","PARTIAL"].includes(i.state)).length)}/><Metric l="Execution engine" v="Live"/><Metric l="SL/TP engine" v="Armed"/></section><section className="grid"><Panel title="Trading accounts">{accounts.slice(0,6).map(a=><Row key={a.id} a={`${a.platform} · ${a.login}`} b={a.connection_status}/>)}</Panel><Panel title="Latest execution activity">{intents.slice(0,8).map(i=><Row key={i.id} a={`${i.side} ${i.canonical_symbol}`} b={i.state}/>)}</Panel></section></>}
function Accounts({items,done}:{items:Account[];done:(s:string)=>void}){const[credential,setCredential]=useState("");async function provision(a:Account){const device=prompt("Unique terminal device ID",`${a.platform}-${a.login}`);if(!device)return;try{const r=await api<{credential:string}>("/terminal/nodes/provision",{method:"POST",body:JSON.stringify({account_id:a.id,device_id:device})});setCredential(r.credential);done("Credential generated. Copy it now; it is shown once.")}catch(e){done(e instanceof Error?e.message:"Provisioning failed")}}return <Panel title="MT4 / MT5 Accounts">{credential&&<pre className="credential">{credential}</pre>}{items.map(a=><div className="table-row" key={a.id}><b>{a.platform}</b><span>{a.broker_name}</span><span>{a.login}</span><span>{a.broker_server}</span><em>{a.connection_status}</em><button onClick={()=>provision(a)}>Provision terminal</button></div>)}</Panel>}
function Orders({accounts,intents,positions,done}:{accounts:Account[];intents:Intent[];positions:Position[];done:(s:string)=>void}){const[f,setF]=useState({account_id:accounts[0]?.id||"",symbol:"EURUSD",side:"BUY",order_type:"MARKET",volume:"0.01",stop_loss:"",take_profit:""});async function send(e:React.FormEvent){e.preventDefault();try{await api("/trades/manual",{method:"POST",body:JSON.stringify({...f,idempotency_key:crypto.randomUUID(),stop_loss:f.stop_loss||undefined,take_profit:f.take_profit||undefined})});done("Trade queued for terminal execution")}catch(q){done(q instanceof Error?q.message:"Trade failed")}}async function close(id:string){if(!confirm("Close this exact position?"))return;await api(`/positions/${id}/close`,{method:"POST",body:JSON.stringify({idempotency_key:crypto.randomUUID()})});done("Priority close queued")}return <><Panel title="Manual trade"><form className="form-grid" onSubmit={send}><select value={f.account_id} onChange={e=>setF({...f,account_id:e.target.value})} required><option value="">Account</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.platform} · {a.login}</option>)}</select><input value={f.symbol} onChange={e=>setF({...f,symbol:e.target.value.toUpperCase()})}/><select value={f.side} onChange={e=>setF({...f,side:e.target.value})}><option>BUY</option><option>SELL</option></select><select value={f.order_type} onChange={e=>setF({...f,order_type:e.target.value})}><option>MARKET</option><option>LIMIT</option><option>STOP</option><option>STOP_LIMIT</option></select><input type="number" step="0.01" min="0.01" value={f.volume} onChange={e=>setF({...f,volume:e.target.value})}/><input placeholder="Stop loss" value={f.stop_loss} onChange={e=>setF({...f,stop_loss:e.target.value})}/><input placeholder="Take profit" value={f.take_profit} onChange={e=>setF({...f,take_profit:e.target.value})}/><button className="trade">Queue trade</button></form></Panel><Panel title="Open positions">{positions.filter(p=>p.is_open).map(p=><div className="table-row" key={p.id}><b>{p.side}</b><span>{p.broker_symbol}</span><span>{p.volume} lots</span><span>Open {p.open_price}</span><span>Live {p.current_price||"—"}</span><button className="danger" onClick={()=>close(p.id)}>Close</button></div>)}</Panel><Panel title="Order lifecycle">{intents.map(i=><Row key={i.id} a={`${i.source} · ${i.action} ${i.canonical_symbol}`} b={i.failure_message||i.state}/>)}</Panel></>}
function Strategies({items,done}:{items:Strategy[];done:(s:string)=>void}){const[n,setN]=useState("");return <Panel title="TradingView Strategies"><form className="inline-form" onSubmit={async e=>{e.preventDefault();try{await api("/strategies",{method:"POST",body:JSON.stringify({name:n,slug:n.toLowerCase().replace(/[^a-z0-9]+/g,"-"),is_active:true,webhook_secret:crypto.randomUUID()+crypto.randomUUID()})});setN("");done("Signed webhook strategy created")}catch(q){done(q instanceof Error?q.message:"Create failed")}}}><input value={n} onChange={e=>setN(e.target.value)} placeholder="Strategy name" required/><button className="trade">Create</button></form>{items.map(s=><Row key={s.id} a={s.name} b={s.is_active?"ACTIVE":"OFF"}/>)}</Panel>}
function Risk({accounts,positions,done}:{accounts:Account[];positions:Position[];done:(s:string)=>void}){return <Panel title="Kill Switch & SL/TP"><p>Stops and targets are evaluated from authenticated terminal snapshots. No position is marked closed until a FILLED event returns.</p>{accounts.map(a=><div className="table-row" key={a.id}><b>{a.login}</b><span>{positions.filter(p=>p.account===a.id&&p.is_open).length} open</span><button className="danger" onClick={async()=>{if(!confirm(`Close every open position on ${a.login}?`))return;try{await api(`/accounts/${a.id}/kill-switch`,{method:"POST",body:"{}"});done("Kill Switch exits queued with priority")}catch(q){done(q instanceof Error?q.message:"Kill Switch failed")}}}>Kill Switch</button></div>)}</Panel>}
function Metric({l,v}:{l:string;v:string}){return <article className="metric"><small>{l}</small><strong>{v}</strong><span>Live tenant data</span></article>}function Panel({title,children}:{title:string;children:React.ReactNode}){return <article className="panel page-panel"><div className="panel-title"><h2>{title}</h2></div>{children}</article>}function Row({a,b}:{a:string;b:string}){return <div className="account"><div><strong>{a}</strong></div><span className="intent-state">{b}</span></div>}
