# Generated by Django 5.2.17 on 2026-09-06 10:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('device_id', models.CharField(max_length=128, unique=True)),
                ('credential_hash', models.CharField(max_length=128)),
                ('credential_prefix', models.CharField(max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sequence', models.PositiveBigIntegerField(default=0)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('agent_version', models.CharField(blank=True, max_length=32)),
                ('terminal_build', models.CharField(blank=True, max_length=32)),
                ('capabilities', models.JSONField(blank=True, default=dict)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='execution_node', to='trading.tradingaccount')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='execution_nodes', to='tenancy.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TerminalCommand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveBigIntegerField()),
                ('kind', models.CharField(choices=[('PLACE', 'Place'), ('MODIFY', 'Modify'), ('CANCEL', 'Cancel'), ('CLOSE', 'Close'), ('CLOSE_ALL', 'Close All'), ('SYNC', 'Sync')], max_length=16)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('CLAIMED', 'Claimed'), ('ACKNOWLEDGED', 'Acknowledged'), ('TERMINAL', 'Terminal')], default='QUEUED', max_length=16)),
                ('priority', models.PositiveSmallIntegerField(default=50)),
                ('payload', models.JSONField(default=dict)),
                ('expires_at', models.DateTimeField()),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commands', to='trading.tradeintent')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commands', to='terminal.executionnode')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terminal_commands', to='tenancy.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='ExecutionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_id', models.UUIDField(unique=True)),
                ('event_type', models.CharField(max_length=24)),
                ('terminal_time', models.DateTimeField()),
                ('payload', models.JSONField(default=dict)),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='execution_events', to='trading.tradeintent')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='execution_events', to='tenancy.tenant')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='terminal.executionnode')),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='terminal.terminalcommand')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccountSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveBigIntegerField()),
                ('captured_at', models.DateTimeField()),
                ('account', models.JSONField(default=dict)),
                ('orders', models.JSONField(default=list)),
                ('positions', models.JSONField(default=list)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_snapshots', to='tenancy.tenant')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='terminal.executionnode')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('node', 'sequence'), name='unique_snapshot_sequence')],
            },
        ),
        migrations.AddIndex(
            model_name='terminalcommand',
            index=models.Index(fields=['node', 'status', 'priority', 'sequence'], name='terminal_te_node_id_dbbb5f_idx'),
        ),
        migrations.AddConstraint(
            model_name='terminalcommand',
            constraint=models.UniqueConstraint(fields=('node', 'sequence'), name='unique_node_sequence'),
        ),
    ]
